# Generated by Django 5.2 on 2025-07-31 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='Amount in paisa (₹1 = 100 paisa)')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('PHONEPE', 'PhonePe'), ('UPI', 'UPI'), ('CARD', 'Card'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet')], max_length=20, null=True)),
                ('phonepe_payment_url', models.URLField(blank=True, help_text='PhonePe checkout URL', null=True)),
                ('phonepe_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phonepe_response', models.JSONField(blank=True, help_text='Raw PhonePe response', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional order metadata')),
                ('redirect_url', models.URLField(help_text='URL to redirect after payment')),
                ('callback_url', models.URLField(blank=True, help_text='Webhook callback URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_refund_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='Refund amount in paisa')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('phonepe_refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phonepe_response', models.JSONField(blank=True, help_text='Raw PhonePe refund response', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.paymentorder')),
            ],
            options={
                'db_table': 'payments_refund',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('REFUND_SUCCESS', 'Refund Success'), ('REFUND_FAILED', 'Refund Failed')], max_length=50)),
                ('merchant_order_id', models.CharField(db_index=True, max_length=100)),
                ('raw_data', models.JSONField(help_text='Raw webhook payload')),
                ('headers', models.JSONField(default=dict, help_text='Webhook headers')),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments_webhook',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['merchant_order_id'], name='payments_we_merchan_33c03a_idx'), models.Index(fields=['event_type', 'processed'], name='payments_we_event_t_7fea2f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['merchant_order_id'], name='payments_or_merchan_8361fd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user', 'status'], name='payments_or_user_id_0f08a8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'created_at'], name='payments_or_status_99bb2e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['merchant_refund_id'], name='payments_re_merchan_6780a6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['payment_order', 'status'], name='payments_re_payment_629707_idx'),
        ),
    ]
