# Generated by Django 5.2 on 2025-07-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='cart_id',
            field=models.CharField(blank=True, db_index=True, help_text='Associated cart ID', max_length=100, null=True),
        ),
    ]
