# Generated by Django 5.2 on 2025-08-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentorder_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='address_id',
            field=models.PositiveIntegerField(blank=True, help_text='Selected address ID for delivery/service', null=True),
        ),
    ]
