# Generated by Django 5.2 on 2025-07-23 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('LOCAL', 'Local Storage'), ('GDRIVE', 'Google Drive'), ('SYSTEM', 'System Path')], default='LOCAL', max_length=10)),
                ('storage_path', models.CharField(default='backups/', help_text='Path where backups will be stored', max_length=500)),
                ('auto_backup_enabled', models.BooleanField(default=True)),
                ('backup_retention_days', models.PositiveIntegerField(default=7, help_text='Number of days to keep backups')),
                ('max_backup_files', models.PositiveIntegerField(default=10, help_text='Maximum number of backup files to keep')),
                ('gdrive_folder_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gdrive_credentials', models.TextField(blank=True, help_text='JSON credentials for Google Drive', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configurations',
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_id', models.CharField(max_length=50, unique=True)),
                ('backup_type', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Automatic'), ('SCHEDULED', 'Scheduled')], default='MANUAL', max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('storage_type', models.CharField(default='LOCAL', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tables_count', models.PositiveIntegerField(default=0)),
                ('records_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Backup',
                'verbose_name_plural': 'Database Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restore_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('restored_tables', models.PositiveIntegerField(default=0)),
                ('restored_records', models.PositiveIntegerField(default=0)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.databasebackup')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restore Log',
                'verbose_name_plural': 'Restore Logs',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
