#!/bin/bash

echo "🚨 CRITICAL: Complete Gunicorn Reset Required"
echo "============================================="
echo ""
echo "The test script works but Swagger fails because"
echo "Gunicorn workers have cached the old code."
echo ""
echo "COPY AND PASTE THESE COMMANDS ON YOUR SERVER:"
echo ""
echo "sudo systemctl stop gunicorn_api_okpuja"
echo "sudo systemctl stop nginx"
echo "sudo pkill -f gunicorn"
echo "sleep 5"
echo "sudo systemctl start gunicorn_api_okpuja"
echo "sleep 10"
echo "sudo systemctl start nginx"
echo ""
echo "Then test in Swagger again - it should work!"
echo "============================================="
