# Generated by Django 5.2 on 2025-06-30 21:43

import astrology.models
import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrologyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('service_type', models.CharField(choices=[('HOROSCOPE', 'Horoscope Analysis'), ('MATCHING', 'Kundali Matching'), ('PREDICTION', 'Future Prediction'), ('REMEDIES', 'Astrological Remedies'), ('GEMSTONE', 'Gemstone Recommendation'), ('VAASTU', 'Vaastu Consultation')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=astrology.models.astrology_service_image_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Astrology Service',
                'verbose_name_plural': 'Astrology Services',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title', 'is_active'], name='astrology_a_title_d01519_idx'), models.Index(fields=['service_type', 'is_active'], name='astrology_a_service_689abb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AstrologyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('birth_place', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('questions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrology_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='astrology.astrologyservice')),
            ],
            options={
                'verbose_name': 'Astrology Booking',
                'verbose_name_plural': 'Astrology Bookings',
                'ordering': ['-preferred_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='astrology_a_user_id_bf1f9e_idx'), models.Index(fields=['preferred_date', 'status'], name='astrology_a_preferr_9f1b74_idx'), models.Index(fields=['service', 'status'], name='astrology_a_service_d521dc_idx')],
            },
        ),
    ]
