# Generated by Django 5.2 on 2025-07-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astrologyservice',
            name='image',
        ),
        migrations.AddField(
            model_name='astrologyservice',
            name='image_card_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='astrologyservice',
            name='image_thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='astrologyservice',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
