# Generated by Django 5.2 on 2025-07-12 11:08

import astrology.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0002_remove_astrologyservice_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrologyservice',
            name='image_card_url',
            field=astrology.models.ImageKitField(blank=True, max_length=500, null=True, verbose_name='Service Card URL'),
        ),
        migrations.AlterField(
            model_name='astrologyservice',
            name='image_thumbnail_url',
            field=astrology.models.ImageKitField(blank=True, max_length=500, null=True, verbose_name='Service Thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='astrologyservice',
            name='image_url',
            field=astrology.models.ImageKitField(blank=True, max_length=500, null=True, verbose_name='Service Image URL'),
        ),
    ]
