# Generated by Django 5.2 on 2025-08-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0003_alter_astrologyservice_image_card_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologybooking',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Payment and booking metadata'),
        ),
    ]
