# Generated by Django 5.1.1 on 2025-08-05 17:48

from django.db import migrations, models
import uuid
from django.utils import timezone


def generate_astro_book_ids(apps, schema_editor):
    """Generate unique astro_book_ids for existing bookings"""
    AstrologyBooking = apps.get_model('astrology', 'AstrologyBooking')
    
    for booking in AstrologyBooking.objects.all():
        # Generate unique astro_book_id
        today = timezone.now().strftime('%Y%m%d')
        unique_id = str(uuid.uuid4().hex[:8]).upper()
        booking.astro_book_id = f"ASTRO_BOOK_{today}_{unique_id}"
        booking.save()


def reverse_generate_astro_book_ids(apps, schema_editor):
    """Reverse migration - set astro_book_ids to None"""
    AstrologyBooking = apps.get_model('astrology', 'AstrologyBooking')
    AstrologyBooking.objects.update(astro_book_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0004_astrologybooking_metadata'),
    ]

    operations = [
        # First add the fields as nullable
        migrations.AddField(
            model_name='astrologybooking',
            name='astro_book_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique astrology booking ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='astrologybooking',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, help_text='Associated payment order ID', max_length=100, null=True),
        ),
        
        # Generate unique IDs for existing records
        migrations.RunPython(generate_astro_book_ids, reverse_generate_astro_book_ids),
        
        # Then make astro_book_id unique and required
        migrations.AlterField(
            model_name='astrologybooking',
            name='astro_book_id',
            field=models.CharField(db_index=True, help_text='Unique astrology booking ID', max_length=100, unique=True),
        ),
        
        # Update status choices
        migrations.AlterField(
            model_name='astrologybooking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20),
        ),
        
        # Add indexes
        migrations.AddIndex(
            model_name='astrologybooking',
            index=models.Index(fields=['astro_book_id'], name='astrology_a_astro_b_4fd499_idx'),
        ),
        migrations.AddIndex(
            model_name='astrologybooking',
            index=models.Index(fields=['payment_id'], name='astrology_a_payment_4170ce_idx'),
        ),
    ]
