# Generated by Django 5.2 on 2025-08-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0006_add_google_meet_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrologybooking',
            name='google_meet_link',
            field=models.URLField(blank=True, help_text='Google Meet link for the astrology session', null=True),
        ),
        migrations.AlterField(
            model_name='astrologybooking',
            name='is_session_scheduled',
            field=models.BooleanField(default=False, help_text='Whether admin has scheduled the session'),
        ),
        migrations.AlterField(
            model_name='astrologybooking',
            name='session_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the session', null=True),
        ),
    ]
