# Generated by Django 5.2 on 2025-08-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0007_add_google_meet_session_fields'),
    ]

    operations = [
    ]
