# Generated by Django 5.2 on 2025-07-15 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_assigned_to'),
        ('cart', '0001_initial'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cart',
            field=models.ForeignKey(default=None, help_text='Cart being purchased', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cart.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=None, help_text='User making the payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Booking created after successful payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='booking.booking'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['cart', 'status'], name='payment_pay_cart_id_eb00b5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payment_pay_user_id_94fc9f_idx'),
        ),
    ]
