# Generated by Django 5.2 on 2025-07-19 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('payment', '0002_payment_cart_payment_user_alter_payment_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cart',
            field=models.ForeignKey(blank=True, help_text='Cart being purchased (can be cleared after successful booking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cart.cart'),
        ),
    ]
