# Generated by Django 5.2 on 2025-07-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='error_code',
            field=models.CharField(blank=True, help_text='Error code from gateway if refund failed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message from gateway if refund failed', null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='merchant_refund_id',
            field=models.CharField(blank=True, help_text='Merchant refund ID for gateways', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='phonepe_refund_id',
            field=models.CharField(blank=True, help_text="PhonePe's refund reference ID", max_length=100, null=True),
        ),
    ]
