# Generated by Django 5.2 on 2025-07-01 17:31

import cms.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='title')),
                ('slug', models.SlugField(help_text='A URL-friendly version of the title', max_length=255, unique=True, verbose_name='URL slug')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(50)], verbose_name='content')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta keywords')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, verbose_name='status')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_current', models.BooleanField(default=True, verbose_name='current version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=cms.models.cms_document_upload_path, verbose_name='attachment')),
                ('requires_consent', models.BooleanField(default=True, verbose_name='requires user consent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'privacy policy',
                'verbose_name_plural': 'privacy policies',
                'ordering': ['-published_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='title')),
                ('slug', models.SlugField(help_text='A URL-friendly version of the title', max_length=255, unique=True, verbose_name='URL slug')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(50)], verbose_name='content')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta keywords')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, verbose_name='status')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_current', models.BooleanField(default=True, verbose_name='current version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=cms.models.cms_document_upload_path, verbose_name='attachment')),
                ('requires_consent', models.BooleanField(default=True, verbose_name='requires user consent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'terms of service',
                'verbose_name_plural': 'terms of service',
                'ordering': ['-published_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('privacy_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_consents', to='cms.privacypolicy')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_consents', to='cms.termsofservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user consent',
                'verbose_name_plural': 'user consents',
            },
        ),
        migrations.CreateModel(
            name='CancellationRefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='title')),
                ('slug', models.SlugField(help_text='A URL-friendly version of the title', max_length=255, unique=True, verbose_name='URL slug')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(50)], verbose_name='content')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta keywords')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, verbose_name='status')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_current', models.BooleanField(default=True, verbose_name='current version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('refund_period_days', models.PositiveSmallIntegerField(default=7, verbose_name='refund period (days)')),
                ('cancellation_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='cancellation fee (%)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'cancellation & refund policy',
                'verbose_name_plural': 'cancellation & refund policies',
                'ordering': ['-published_at', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['slug'], name='cms_cancell_slug_bbb0b3_idx'), models.Index(fields=['status'], name='cms_cancell_status_05c00c_idx'), models.Index(fields=['is_current'], name='cms_cancell_is_curr_c8590e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='privacypolicy',
            index=models.Index(fields=['slug'], name='cms_privacy_slug_b5a1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='privacypolicy',
            index=models.Index(fields=['status'], name='cms_privacy_status_63e1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='privacypolicy',
            index=models.Index(fields=['is_current'], name='cms_privacy_is_curr_cef007_idx'),
        ),
        migrations.AddIndex(
            model_name='termsofservice',
            index=models.Index(fields=['slug'], name='cms_termsof_slug_9bd3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='termsofservice',
            index=models.Index(fields=['status'], name='cms_termsof_status_61cca8_idx'),
        ),
        migrations.AddIndex(
            model_name='termsofservice',
            index=models.Index(fields=['is_current'], name='cms_termsof_is_curr_39fc4d_idx'),
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['user'], name='cms_usercon_user_id_f407e5_idx'),
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['consented_at'], name='cms_usercon_consent_48e72b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userconsent',
            unique_together={('user', 'terms', 'privacy_policy')},
        ),
    ]
