# Generated by Django 5.2 on 2025-07-06 19:27

import django.db.models.deletion
import puja.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('HINDI', 'Hindi'), ('ENGLISH', 'English'), ('SANSKRIT', 'Sanskrit'), ('REGIONAL', 'Regional')], default='HINDI', max_length=10)),
                ('package_type', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('CUSTOM', 'Custom')], default='STANDARD', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR', max_digits=10)),
                ('description', models.TextField()),
                ('includes_materials', models.BooleanField(default=False, help_text='Does this package include puja materials?')),
                ('priest_count', models.PositiveSmallIntegerField(default=1, help_text='Number of priests required')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Package',
                'verbose_name_plural': 'Service Packages',
                'ordering': ['puja_service', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PujaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Puja Category',
                'verbose_name_plural': 'Puja Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PujaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('image', models.ImageField(upload_to=puja.models.puja_service_image_path)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('HOME', 'At Home'), ('TEMPLE', 'At Temple'), ('ONLINE', 'Online')], default='HOME', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Approximate duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='puja.pujacategory')),
            ],
            options={
                'verbose_name': 'Puja Service',
                'verbose_name_plural': 'Puja Services',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PujaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('special_instructions', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='puja.package')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puja_bookings', to=settings.AUTH_USER_MODEL)),
                ('puja_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='puja.pujaservice')),
            ],
            options={
                'verbose_name': 'Puja Booking',
                'verbose_name_plural': 'Puja Bookings',
                'ordering': ['-booking_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='puja_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='puja.pujaservice'),
        ),
        migrations.AddIndex(
            model_name='pujaservice',
            index=models.Index(fields=['title', 'is_active'], name='puja_pujase_title_116b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='pujaservice',
            index=models.Index(fields=['category', 'is_active'], name='puja_pujase_categor_54cadd_idx'),
        ),
        migrations.AddIndex(
            model_name='pujabooking',
            index=models.Index(fields=['user', 'status'], name='puja_pujabo_user_id_637f51_idx'),
        ),
        migrations.AddIndex(
            model_name='pujabooking',
            index=models.Index(fields=['booking_date', 'status'], name='puja_pujabo_booking_c2fe15_idx'),
        ),
        migrations.AddIndex(
            model_name='pujabooking',
            index=models.Index(fields=['puja_service', 'status'], name='puja_pujabo_puja_se_9e9fe6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('puja_service', 'language', 'package_type')},
        ),
    ]
