# Generated by Django 5.2 on 2025-07-10 10:26

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pujaservice',
            name='image',
            field=accounts.models.ImageKitField(blank=True, max_length=500, null=True, verbose_name='image URL'),
        ),
    ]
