# Generated by Django 5.2 on 2025-07-07 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-updated_at'], 'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='pancard',
            options={'ordering': ['-updated_at'], 'verbose_name': 'PAN Card', 'verbose_name_plural': 'PAN Cards'},
        ),
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ['-created_at'], 'verbose_name': 'SMS Log', 'verbose_name_plural': 'SMS Logs'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-updated_at'], 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AddField(
            model_name='smslog',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['phone'], name='accounts_sm_phone_646b85_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['status'], name='accounts_sm_status_0abf10_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['created_at'], name='accounts_sm_created_30b75f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='accounts_us_phone_f54457_idx'),
        ),
    ]
