# Generated by Django 5.2 on 2025-07-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Administrator'), ('EMPLOYEE', 'Employee/Priest')], default='USER', max_length=20, verbose_name='role'),
        ),
    ]
