# Generated by Django 5.2 on 2025-07-07 00:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_options_alter_pancard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter 10-digit Indian phone number (starting with 6-9)', max_length=15, null=True, unique=True, validators=[accounts.models.validate_indian_phone_number], verbose_name='phone number'),
        ),
    ]
