# Generated by Django 5.2 on 2025-08-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark for easy identification', max_length=255, null=True, verbose_name='landmark'),
        ),
    ]
