# Generated by Django 5.2 on 2025-08-03 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_address'),
        ('payments', '0003_add_address_to_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Payment order associated with this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='payments.paymentorder'),
        ),
    ]
