# Generated by Django 5.2 on 2025-08-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_order_id',
            field=models.CharField(blank=True, help_text='Payment order ID associated with this booking', max_length=100, null=True),
        ),
    ]
