# Generated by Django 5.2 on 2025-07-06 19:27

import misc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('subject', models.CharField(choices=[('GENERAL', 'General Inquiry'), ('SERVICE', 'Service Inquiry'), ('BOOKING', 'Booking Issue'), ('PAYMENT', 'Payment Issue'), ('TECHNICAL', 'Technical Issue'), ('JOB', 'Job Application'), ('OTHER', 'Other')], default='GENERAL', max_length=20, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REPLIED', 'Replied'), ('CLOSED', 'Closed')], default='PENDING', max_length=10, verbose_name='status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='replied at')),
            ],
            options={
                'verbose_name': 'contact us message',
                'verbose_name_plural': 'contact us messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='misc_contac_status_8a1188_idx'), models.Index(fields=['subject'], name='misc_contac_subject_5d5daa_idx'), models.Index(fields=['created_at'], name='misc_contac_created_2092eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('original_image', models.ImageField(upload_to=misc.models.event_image_upload_path, verbose_name='image')),
                ('event_date', models.DateField(verbose_name='event date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('registration_link', models.URLField(blank=True, null=True, verbose_name='registration link')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured event')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-event_date', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='misc_event_slug_8c3459_idx'), models.Index(fields=['status'], name='misc_event_status_ce7ac6_idx'), models.Index(fields=['is_featured'], name='misc_event_is_feat_91fa0b_idx'), models.Index(fields=['event_date'], name='misc_event_event_d_34af06_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='responsibilities')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='requirements')),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('VOLUNTEER', 'Volunteer')], default='FULL_TIME', max_length=20, verbose_name='job type')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='salary range')),
                ('application_deadline', models.DateTimeField(verbose_name='application deadline')),
                ('application_link', models.URLField(blank=True, null=True, verbose_name='application link')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'job opening',
                'verbose_name_plural': 'job openings',
                'ordering': ['-application_deadline', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='misc_jobope_slug_e170b9_idx'), models.Index(fields=['job_type'], name='misc_jobope_job_typ_81b014_idx'), models.Index(fields=['is_active'], name='misc_jobope_is_acti_c1a9c8_idx'), models.Index(fields=['application_deadline'], name='misc_jobope_applica_47de69_idx')],
            },
        ),
    ]
