# Generated by Django 5.2 on 2025-08-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imagekit_banner_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ImageKit Banner URL'),
        ),
        migrations.AddField(
            model_name='event',
            name='imagekit_original_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ImageKit Original URL'),
        ),
        migrations.AddField(
            model_name='event',
            name='imagekit_thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ImageKit Thumbnail URL'),
        ),
    ]
