# Generated by Django 5.2 on 2025-08-03 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected_address',
            field=models.ForeignKey(blank=True, help_text='Selected address for service delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='accounts.address'),
        ),
    ]
