# Generated by Django 5.2 on 2025-08-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_selected_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='selected_address',
        ),
    ]
