name: Deploy Django DRF API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@157.173.221.192 << 'ENDSSH'
            cd /opt/api.okpuja.com
            git fetch origin main
            git reset --hard origin/main  # Always use repo HEAD, discard local changes
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py makemigrations --noinput
            python manage.py migrate --noinput
            
            # Seed database with fresh test data (clear previous data)
            echo "🌱 Seeding database with fresh test data..."
            python manage.py seed_blog_data --clear --categories 8 --posts 50 --users 10
            python manage.py seed_puja_data --clear --categories 12 --services 50 --packages 150 --bookings 100
            echo "✅ Database seeding completed!"
            
            python manage.py collectstatic --noinput
            systemctl restart nginx
            systemctl restart gunicorn_api_okpuja
            sudo systemctl restart nginx
          ENDSSH
